from tkinter import *
root = Tk()
root.geometry('230x350+500+100')
root.title('Width e Height')
root.resizable(width=False, height=False)
root.minsize(width=380, height=280)
root.maxsize(width=500, height=400)
root.config(bg='black')
l1 = Label(root, text='OOO', bg='black', fg='red', width=1)
l2 = Label(root, text='OOO', bg='black', fg='red', width=2)
l3 = Label(root, text='OOO', bg='black', fg='red', width=3)
l4 = Label(root, text='O\nO\nO', bg='black', fg='red', height=1)
l5 = Label(root, text='O\nO\nO', bg='black', fg='red', height=2)
l6 = Label(root, text='O\nO\nO', bg='black', fg='red', height=3)
l1.pack(pady=15)
l2.pack(pady=15)
l3.pack(pady=15)
l4.pack(pady=15)
l5.pack(pady=15)
l6.pack(pady=15)
root.mainloop()
