from tkinter import *
janela = Tk()
janela.geometry('330x330')
l1 = Label(janela, text='Fonte I', font='Times 12 bold italic')
l2 = Label(janela, text='Fonte II', font='Garamond 18 underline bold')
l3 = Label(janela, text='Fonte III', font='Times 20')
l4 = Label(janela, text='Fonte IV', font='Consolas 10 overstrike')
l5 = Label(janela, text='Fonte V', font='Courier 25 underline')
l6 = Label(janela, text='Fonte VI', font='Arial 18 italic overstrike')
l1.pack(pady=10)
l2.pack(pady=10)
l3.pack(pady=10)
l4.pack(pady=10)
l5.pack(pady=10)
l6.pack(pady=10)
janela.mainloop()
