from tkinter import Tk, Label, RAISED, RIDGE, GROOVE
janela = Tk()
janela.title('Relief e Border')
janela.resizable(width=False, height=False)
janela.geometry('300x400+500+100')
t20 = 'Times 20 bold'
l1 = Label(janela, text='flat', font=t20, relief='flat', border=5, highlightbackground='#00ff00', highlightthickness=2)
l2 = Label(janela, text='solid', font=t20, relief='solid', border=5, highlightbackground='#00ff00', highlightthickness=2)
l3 = Label(janela, text='sunken', font=t20, relief='sunken', border=5,  highlightbackground='#00ff00', highlightthickness=2)
l4 = Label(janela, text='raised', font=t20, relief=RAISED, bd=5, highlightbackground='#00ff00', highlightthickness=2)
l5 = Label(janela, text='ridge', font=t20, relief=RIDGE, bd=5, highlightbackground='#00ff00', highlightthickness=2)
l6 = Label(janela, text='groove', font=t20, relief=GROOVE, bd=5, highlightbackground='#00ff00', highlightthickness=2)
l1.pack(pady=10)
l2.pack(pady=10)
l3.pack(pady=10)
l4.pack(pady=10)
l5.pack(pady=10)
l6.pack(pady=10)
janela.mainloop()
